package guis;

import entidades.Apuestas;
import entidades.Casilla;
import entidades.Dado;
import entidades.Ficha;
import entidades.Jugador;
import entidades.Partida;
import entidades.Tablero;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 * Luis Gonzalo Cervantes Rivera 00000228549
 * Gabriel Francisco Piñuelas Ramos 00000230626
 * Ricardo Pacheco Urias 00000229178
 * Abraham Sered Gómez Martínez 00000228796
 * 
 */
public class DlgUnirsePartida extends javax.swing.JDialog {

    /**
     * Creates new form DlgUnirsePartida
     */
    public DlgUnirsePartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoTextoIP = new javax.swing.JTextField();
        botonUnirse = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unirse a partida");

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel1.setText("Introduzca la dirección IP que el anfitrió le proporcionó para unirse a la partida");

        botonUnirse.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        botonUnirse.setText("Unirse");
        botonUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnirseActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel2.setText("Unirse a Partida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoTextoIP)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonUnirse)
                                .addGap(193, 193, 193)
                                .addComponent(botonCancelar)))
                        .addGap(107, 107, 107))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(206, 206, 206)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(campoTextoIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonUnirse))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnirseActionPerformed
        if (verificarIP()) {
            Partida partida = this.obtenerPartida();
            unirPartida(partida);
            System.out.println("numJugadors: " + 2);
            FrmPartida10.LblnumJugadores.setText(" " + 2);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "La ip donde se encuentra la partida es 127.0.0.1", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonUnirseActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_botonCancelarActionPerformed

    public boolean verificarIP() {
        String ip = this.campoTextoIP.getText();
        
        return ip.equals("127.0.0.1");
    }
    
    public void unirPartida(Partida partida) {
        FrmPartida10 frmPartida = new FrmPartida10(partida);
        frmPartida.setVisible(true);
        this.setVisible(false);
    }
    
    public Partida obtenerPartida() {
        Apuestas apuestas = new Apuestas(500000, 5);
        Tablero tablero = new Tablero(this.llenarCasillas(10 * 2 * 4 + 4, 2));
        Jugador[] jugadores = this.llenarJugadores(2, apuestas);
        
        for (Jugador j : jugadores) {
            j.setFichas(this.llenarFichas(2, j));
        }
        
        return new Partida(10, tablero, jugadores, this.llenarDados());
    }
    
    public Casilla[] llenarCasillas(int numCasillas, int numFichas) {
        Casilla[] casillas = new Casilla[numCasillas];
        for (int i = 1; i < numCasillas; i++) {
            casillas[i - 1] = new Casilla(i, new Ficha[numFichas]);
        }
        return casillas;
    }
    
    public Jugador[] llenarJugadores(int numJugadores, Apuestas apuesta) {
        Jugador[] jugadores = new Jugador[numJugadores];
        for (int i = 1; i < numJugadores + 1; i++) {
            jugadores[i - 1] = new Jugador(apuesta);
        }
        return jugadores;
    }
    
    public Ficha[] llenarFichas(int numFichas, Jugador jugador) {
        Ficha[] fichas = new Ficha[numFichas];
        for (int i = 1; i < numFichas + 1; i++) {
            fichas[i - 1] = new Ficha(i - 1, -1);
        }
        return fichas;
    }
    
    public Dado[] llenarDados() {
        Dado[] dados = new Dado[5];
        for (int i = 0; i < 5; i++) {
            Dado dado = new Dado();
            dados[i] = dado;
        }
        return dados;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonUnirse;
    private javax.swing.JTextField campoTextoIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
